<?php if(!defined('KIRBY')) exit ?>

title: Website
pages: default
fields:
  title:
    label: Title of website
    type: text
    width: 1/2
  titlesuffix:
    label: Title suffix (Optional)
    type: text
    width: 1/2
  author:
    label: Author of website
    type: text
    width: 1/2
  logoimg:
    label: Logo
    type: image
  footer:
    label: Footer
    type: textarea
    help: <i class="fa fa-lightbulb-o"></i> <a href="/assets/docs/kirbytext101.html" target="_blank">Text formatting with Kirby</a>
  description:
    label: Meta description
    type: textarea
    buttons: false
  info1:
    label: Search engine optimization (SEO)
    type: info
    text: The following declarations are global, unless overwritten individually on another page (if available). <ul><li><strong>Title suffix:</strong> You should not use more than 65 characters including blank space here.</li><li><strong>Meta description:</strong> You should not use more than 159 characters including blank space here.</li></ul>
